# This file defines single architecture set for tlut systolic array performance projection
- proj_16_16_bank4_block16
- proj_32_32_bank4_block16
- proj_64_64_bank4_block16
- proj_128_128_bank4_block16
