arch:
  arithmetic:
    dimI: 128 
    dimW: 128
    bwI: 4
    bwW: 8
    instances: 1
  storage:
  - name: OutputBuffer
    bw: 32
    entries: 16384
    instances: 1
    layout: NKPQ
  - name: WeightBuffer
    bw: 8
    entries: 128
    instances: 1
    layout: KRSC
  - name: InputBuffer
    bw: 4
    entries: 128
    instances: 1
    layout: NCHW

