arch:
  arithmetic:
    dimI: 128
    dimW: 2
    bwI: 4
    bwW: 8
    instances: 1
  storage:
  - name: OutputBuffer
    bw: 4
    base: 2000000
    entries: 1000000
    instances: 1
    layout: NKQP
    bank: 16
    block: 64
  - name: WeightBuffer
    bw: 8
    base: 1000000
    entries: 1000000
    instances: 1
    layout: RSCK
    bank: 16
    block: 64
  - name: InputBuffer
    bw: 4
    base: 0
    entries: 1000000
    instances: 1
    layout: NCHW
    bank: 16
    block: 64

