arch:
  - block: 32
    name:
    - arch_tlut_systolic_projection_bank16_block32
    - arch_tlut_systolic_projection_bank8_block32
    - arch_tlut_systolic_projection_bank4_block32
  - block: 16
    name: 
    - arch_tlut_systolic_projection_bank16_block16
    - arch_tlut_systolic_projection_bank8_block16
    - arch_tlut_systolic_projection_bank4_block16
  - block: 8
    name: 
    - arch_tlut_systolic_projection_bank16_block8
    - arch_tlut_systolic_projection_bank8_block8
    - arch_tlut_systolic_projection_bank4_block8
  
workloads:
  - convnet
  - alexnet
dataflow:
  - dtfs